apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vtlib

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: acq-mcp-config
    envs:
      - generated/config.env

secretGenerator:
  - name: acq-mcp-secret
    envs:
      - generated/secret.env
  - name: acq-mcp-registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=generated/dockerconfigjson

patches:
  - path: generated/deployment-image-patch.yaml
  - path: generated/ingress-patch.yaml
